import "./globals.css";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="logo-container">
            <Image src="/Struktor Jesic.png" alt="Struktor Logo" fill={true} />
          </div>
          <h1>Hello Site</h1>
        </nav>
        {children}
        <nav>
          <h1>Goodbye Site</h1>
        </nav>
      </body>
    </html>
  );
}
